cluster_name: local-default
provider:
    type: local
    head_ip:  128.84.80.37
    worker_ips: [128.84.80.38]
auth: {ssh_user: eugene, ssh_private_key: ~/.ssh/id_rsa}
## Typically for local clusters, min_workers == max_workers.
min_workers: 2
max_workers: 2
setup_commands:  # Set up each node.
    - conda activate ffcv && echo 'conda activate ffcv' >> ~/.bashrc
# Patterns for files to exclude when running rsync up or rsync down
#rsync_exclude:
#    - "**/.git"
#    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"
