cluster_name: local-default
provider:
    type: local
    head_ip: 128.84.84.8
    worker_ips: [128.84.87.101, 128.84.84.162]
auth: {ssh_user: eugene, ssh_private_key: ~/.ssh/id_rsa}
## Typically for local clusters, min_workers == max_workers.
min_workers: 2
max_workers: 2
setup_commands:  # Set up each node.
    - conda activate pt && echo 'conda activate pt' >> ~/.bashrc