project: "all_mix"
name: "CLEAN_ALL"
dataset: "Imagenet"

task: Imagenet

data_path: /home/eugene/data/imagenet/

synthesizers:
  - SinglePixel
  - Memory
  - Pattern
  - Complex
  - Primitive
  - Dynamic
#  - Clean

main_synthesizer: Pattern

batch_size: 128
test_batch_size: 100
lr: 0.001
momentum: 0.9
decay: 0.0005
epochs: 10
save_on_epochs: []
optimizer: Adam
log_interval: 100

scheduler: False
pretrained: False
max_batch_id: 100000

multi_objective_metric: accuracy
multi_objective_alpha: 0.9

batch_clip: False
#saved_grads: True
grad_sigma: 0.0
grad_clip: 1000
label_noise: 0.0
transform_erase: 0.0
transform_sharpness: 0.0
backdoor_cover_percentage: 0.05

random_seed: 35
poisoning_proportion: 10
backdoor_labels:
  SinglePixel: 9
  Dynamic: 8
  Pattern: 1
  Primitive: 6
  Memory: 7
  Clean: 3
  Complex: -1

backdoor: True

loss_balance: none
mgda_normalize: loss+

save_model: False
log: False
tb: False

transform_train: True


loss_tasks:
  - normal
#  - neural_cleanse
#  - sentinet_evasion


#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588