task: MNISTFed
synthesizers:
  - Primitive
dataset: "mnist"

backdoor_cover_percentage: 0.1

data_path: /home/${USER}/irontorch/.data


batch_size: 64
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 10
save_on_epochs: []
optimizer: SGD
log_interval: 100

pretrained: False

scheduler: False
multi_objective_metric: accuracy
multi_objective_alpha: 0.9

backdoor_labels:
  SinglePixel: 9
  Dynamic: 8
  Pattern: 1
  Primitive: 6
  Memory: 7
  Clean: 3
  Complex: -1

#resume_model: model_CifarFed_Nov.26_20.32.44_no_attack_fl/model

loss_balance: MGDA
mgda_normalize: none

save_model: False
log: False
tb: False
report_train_loss: False

transform_train: True
random_seed: 5

fl: True
fl_no_models: 10
fl_local_epochs: 2
fl_total_participants: 100
fl_eta: 10
fl_sample_dirichlet: False
fl_dirichlet_alpha: None
fl_diff_privacy:  False
fl_dp_clip: None
fl_dp_noise: None

backdoor: True
poisoning_proportion: 0
fl_number_of_adversaries: 100
fl_weight_scale: 1
#fl_single_epoch_attack: 1


loss_tasks:
  - backdoor
#  - normal
#  - nc_adv
#  - ewc
#  - latent
#  - latent_fixed


#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588