project: "test"
name: "test"

task: MNIST
synthesizer: Pattern

#resume_model: model_MNIST_grid/model_last.pt.tar


grad_sigma: 0.01
grad_clip: 1
opacus: False
saved_grads: False
compute_grads_only: False
batch_clip: True
#max_batch_id: 100

batch_size: 100
test_batch_size: 100
lr: 0.001
momentum: 0.9
decay: 0.0000
epochs: 6
save_on_epochs: []
optimizer: Adam
log_interval: 100
scheduler: False

recover_indices: /tmp/weights.pt

poisoning_proportion: 0.1
backdoor_label: 8
backdoor: True
backdoor_dynamic_position: False
clean_label: False
cut_grad_threshold: 10

loss_balance: MGDA
mgda_normalize: loss

save_model: False
log: True
tb: False
wandb: True

transform_train: True


loss_tasks:
#  - backdoor
  - normal
#  - neural_cleanse
#  - sentinet_evasion

