project: "mnist_exps"
name: "sweep"

task: MNIST
synthesizer: SinglePixel
data_path: /home/eugene/irontorch/.data

#resume_model: model_MNIST_no_attack_init/model_last.pt.tar

grad_sigma: 0.0
grad_clip: 1000
batch_clip: False
label_noise: 0.0

#opacus: True
#saved_grads: True
#max_batch_id: 100

batch_size: 64
test_batch_size: 100
lr: 0.01
momentum: 0.9
decay: 0.0005
epochs: 10
save_on_epochs: []
optimizer: SGD
log_interval: 100
#scheduler: StepLR
drop_label_proportion: 0.9
drop_label: 5


#pre_compute_grads: True
#cosine_batching: True
#sampling_model_epochs: 5
#gradient_layer: fc2.weight

#recover_indices: /tmp/weights_0.01.pt
#clamp_norms: 10
#pow_weight: 4
#cut_grad_threshold: 30
#subset_training:
#  part: 1000
multi_objective_metric: accuracy
multi_objective_alpha: 0.9

poisoning_proportion: 100
backdoor_label: 9
backdoor: True
backdoor_dynamic_position: False
clean_label: False
#backdoor_cover_percentage: 0.1
random_seed: 6

loss_balance: MGDA
mgda_normalize: loss

save_model: False
#log: True
wandb: False
#plot_conf_matrix: True
#tb: False

transform_train: True


loss_tasks:
#  - backdoor
  - normal
#  - neural_cleanse
#  - sentinet_evasion

