project: "sweep2"
program: "training.py"
name: "multi_obj_001"
method: bayes
metric:
  goal: maximize
  name: multi_objective
parameters:
  batch_size:
    values: [64]
  lr:
    values: [0.0248]
  optimizer:
    values: ['SGD']
  decay:
    values: [0.000003]
  momentum:
    values: [0.81]
  poisoning_proportion:
    values: [0.0007]
#  label_noise:
#    values: [0.1, 0.3, 0.5]

  random_seed:
    values: [ 1, 2, 3, 4, 5, 6, 7, 8, 9]
command:
  - ${env}
  - python
  - ${program}
  - "--params"
  - "configs/mnist_params.yaml"