project: "sweep2"
program: "training.py"
name: "multi_obj"
method: bayes
metric:
  goal: maximize
  name: multi_objective
parameters:
  batch_size:
    values: [64, 256, 512]
  lr:
    values: [0.1, 0.01, 0.001]
  optimizer:
    values: ['Adam', 'SGD']
  decay:
    values: [0.0005, 0.00005, 0.005]
#  momentum:
#    values: [0.8, 0.9, 0.95]
#  random_seed:
#    values: [1, 2, 3, 4, 5]
#  poisoning_proportion:
#    values: [0.001, 0.005, 0.01]
command:
  - ${env}
  - python
  - ${program}
  - "--params"
  - "configs/mnist_params.yaml"