project: "sweep"
program: "training.py"
name: "hyperparams2"
method: grid
metric:
  goal: minimize
  name: Test_Backdoor_Accuracy_Top-1
parameters:
  batch_size:
    values: [16, 32, 64, 128, 256, 512]
  lr:
    values: [0.1, 0.01, 0.001]
  epochs:
    values: [10]
  optimizer:
    values: ['Adam', 'SGD']
  decay:
    values: [0.0005, 0.0001, 0.00005, 0.001]
  momentum:
    values: [0.8, 0.9, 0.95]
  random_seed:
    values: [1, 2, 3, 4, 5]
command:
  - ${env}
  - python
  - ${program}
  - "--params"
  - "configs/mnist_params.yaml"